# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # defaults:
       # run:
         # working-directory: ./server

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Server Dependencies Compatibility
    - working-directory: /server
    - uses: actions/checkout@v3
    - name: Node>${{ matrix.node-version }} Server Dependencies Compatibility
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - run: npm i
    - run: npm ci
    - run: npm run build --if-present
    
    # Client Dependencies Compatibility
    - working-directory: /client
    - uses: actions/checkout@v3
    - name: Node>${{ matrix.node-version }} Client Dependencies Compatibility
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
    - run: npm i
    - run: npm ci
    - run: npm run build --if-present
    
    - name: action-git-diff-suggestions
    # You may pin to the exact commit or the version.
    # uses: getsentry/action-git-diff-suggestions@8c75946d0d7bbe80a92cf3579d544321512c30b7
      uses: getsentry/action-git-diff-suggestions@v1
      with:
        # github token
        # github-token: optional
        # The message to prepend the review suggestion
        message: "Code Reviewed"
